
backend:
  name: git-gateway
  branch: main
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "site"
    label: "Site Content"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "content/homepage.md"
        fields:
          - {label: Headline, name: headline, widget: string}
          - {label: Tagline, name: tagline, widget: text}
